server:
  port: 9002
spring:
  application:
    name: daniu-file
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
feign:
  hystrix:
    enabled: true

FILE_SERVER_URL: http://192.168.5.134:8080/