server:
  port: 9006
spring:
  application:
    name: daniu-item-web
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    instance:
      prefer-ip-address: true
feign:
  hystrix:
    enabled: true
# 生成静态页的位置
pagepath: D:\\items