server:
  port: 9004
spring:
  application:
    name: search
  elasticsearch:
    rest:
      uris: 192.168.5.134:9200  #此处配置elasticsearch的访问地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#超时配置
ribbon:
  ReadTimeout: 300000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000